apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: road-monitor

bases:
  - ../../base

commonLabels:
  environment: production

replicas:
  - name: backend
    count: 3
  - name: frontend
    count: 2

patchesStrategicMerge:
  - mongodb-patch.yaml

images:
  - name: road-monitor-backend
    newTag: v1.0.0
  - name: road-monitor-frontend
    newTag: v1.0.0