apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: road-monitor
  labels:
    app: backend
data:
  MONGO_URL: "mongodb://mongodb:27017"
  MONGO_DB_NAME: "road_monitor"
  LOG_LEVEL: "INFO"
  DEBUG: "False"
  CLUSTER_RADIUS: "1.0"