apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  namespace: road-monitor
  labels:
    app: frontend
data:
  EXPO_PUBLIC_BACKEND_URL: "http://backend:8001"
  REACT_APP_BACKEND_URL: "http://backend:8001"
  EXPO_DEVTOOLS_LISTEN_ADDRESS: "0.0.0.0"
  NODE_ENV: "production"