apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: road-monitor

resources:
  - namespace.yaml
  - mongodb-pvc.yaml
  - mongodb-deployment.yaml
  - mongodb-service.yaml
  - backend-configmap.yaml
  - backend-deployment.yaml
  - backend-service.yaml
  - backend-hpa.yaml
  - frontend-configmap.yaml
  - frontend-deployment.yaml
  - frontend-service.yaml
  - frontend-hpa.yaml
  - ingress.yaml

commonLabels:
  app.kubernetes.io/name: road-monitor
  app.kubernetes.io/version: "1.0.0"
  app.kubernetes.io/managed-by: kustomize